Admin panel merge test
tomered/smart-campus-frontend pull request #21
Opened 2024-10-10 11:16 UTC by galtouti

2024-10-28 17:46 UTC, yuvalelarat commented
connected the frontend admin pages to the backend using redux and changed the index.js + store.js files as tomer told me to

there are some comments for the things that i have added in the componenets, they are written in english.

as you asked i used useEffect instead of refetch(),
let me know if there's something wrong/missing.

2024-10-31 13:18 UTC, yuvalelarat commented
ready for review

2024-11-02 05:31 UTC, tomered requested changes
Please write comments only in English

2024-11-02 20:51 UTC, yuvalelarat commented
ready for 2nd review

2024-11-02 21:05 UTC, tomered requested changes

2024-11-02 21:05 UTC, tomered commented on src/components/screens/AdminPage/AdminAlertCenter.jsx
> +              {/* רשימת התראות */}
Please write comments only in English

2024-11-02 21:12 UTC, yuvalelarat commented on src/components/screens/AdminPage/AdminAlertCenter.jsx
> +              {/* רשימת התראות */}
done

2024-11-02 21:26 UTC, tomered approved these changes

2024-11-02 21:49 UTC, merged